name: recollida_selectiva
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - r-base=4.5.2
  - r-data.table
  - r-dplyr
  - r-ggplot2
  - r-kableextra
  - r-knitr
  - r-languageserver
  - r-rmarkdown